#!/bin/bash

echo -e "\033[36m Configurações Iniciais ...\033[m"
#mkdir -p  /opt/leitor_pdf/Avaliacao && echo "Criando Pasta ..." || exit 1
# Biblioteca necessaria 
pip3 install pypdf && echo -e "\033[36m Efetuado com Sucesso !!!\033[m" || echo -e "\033[m31 Algo Falhou na Instalação $2 ):!\033[m"




