.\"Isso é um comentário
.TH DECIMO14 "04 Março de 2025" "Versão 0.2" " Manual de uso"

.SH NOME
decimo14 - Gerar uma lista em PDF com a Pontuação de Todos os Agentes da SEMOB.

.SH RESUMO
.B decimo14
[\-h] [\-\-help] [-v] [\-\-version] 

.SH DESCRIÇÃO
.PP
decimo14 é um programa escrito em python para extrair dados de uma tabela em formato PDF, armazenamento no Banco de Dados(Sqlite3) e geração de uma lista com a pontuação atualizada mês a mês dos agentes de trânsito.

.SH OPÇÕES
decimo14 aceita as seguintes opções:
.TP 8
.B  \-h, \-\-help
Exibe a mensagem de ajuda do programa e sai.
.TP 8
.B \-v, \-\-version
Exibe a versão do programa.

.PP
EXEMPLOS:

	~$ decimo14 -h ou --help
	~$ decimo14 -v ou --version

.B CABECALHO__USER__EMAIL
eduardomartineznunes@gmail.com.
.TP 8
.B CABECALHO__USER__LICENCA
Licensa de uso é a GNU 3.0 .

.SH AUTORES
Eduardo Martinez.

Contato:

-Página no github (edmartineznunes) https://github.com/edmartineznunes


